import os
import subprocess

def parse_prompt(prompt):
    """
    Parses the natural language prompt to extract game parameters.
    """
    # For now, we'll use a simple placeholder implementation
    print(f"Parsing prompt: '{prompt}'")
    return {"entities": ["player", "platform", "spike_trap", "key"]}

def generate_godot_project(params):
    """
    Generates the Godot project files.
    """
    print("Generating Godot project...")
    # Create a directory for the project
    project_path = r"c:\Users\kande\Desktop\New folder\GadotGameBuilder\output\game"
    export_path = r"c:\Users\kande\Desktop\New folder\GadotGameBuilder\output\game_export\index.html".replace("\\", "/")
    os.makedirs(os.path.dirname(export_path), exist_ok=True)
    os.makedirs(project_path, exist_ok=True)
    print(f"Created project directory at: {project_path}")

    # Create project.godot file
    with open(os.path.join(project_path, "project.godot"), "w") as f:
        f.write("""config_version=5

[application]
config/name="AI Game-Smith Game"
config/description="A game generated by AI Game-Smith"
config/version="0.1"
config/icon="res://icon.svg"

[display]
window/size/viewport_width=1280
window/size/viewport_height=720

[physics]
2d/default_gravity=980
""")

    # Create export_presets.cfg
    with open(os.path.join(project_path, "export_presets.cfg"), "w") as f:
        f.write(f"""[preset.0]
name="HTML5"
platform="Web"
runnable=true
export_path="{export_path}"

[preset.0.options]
custom_template/debug=""
custom_template/release=""
""")
    return project_path

def compile_and_deploy(project_path):
    """
    Compiles the Godot project and deploys it.
    """
    print("Compiling and deploying...")
    # NOTE: You may need to change this to the actual path of your Godot executable
    godot_executable = r"C:\Users\kande\Downloads\Godot_v4.5.1-stable_win64.exe\Godot_v4.5.1-stable_win64.exe"

    # Run Godot in headless mode to export the project
    result = subprocess.run([godot_executable, "--headless", "--export-release", "HTML5"], cwd=project_path, capture_output=True, text=True)

    if result.returncode != 0:
        print("Godot export failed:")
        print(result.stderr)
    else:
        print("Compilation finished. The exported game can be found in the 'game_export' directory.")
    # 2. Use git to push the exported game to GitHub Pages.

def main():
    """
    Main function for the AI Game-Smith system.
    """
    prompt = "A level with ice platforms and a single spike trap guarding a key"
    
    # 1. Parse the prompt
    game_parameters = parse_prompt(prompt)
    
    # 2. Generate the Godot project
    project_path = generate_godot_project(game_parameters)
    
    # 3. Compile and deploy
    if project_path:
        compile_and_deploy(project_path)

if __name__ == "__main__":
    main()
